edition = "2021"
hard_tabs = true
merge_derives = true
reorder_imports = true
reorder_modules = true
use_field_init_shortland = true
use_small_heuristics = "Off"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 100